[project]
name = "cryolvix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram[i18n]==3.25.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "cachetools>=7.0.1",
    "fluent-compiler>=1.1",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "rich>=14.3.2",
    "sqlalchemy>=2.0.46",
]
